version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: polls
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: .
    environment:
      DATABASE_URL: postgresql://postgres:password@db/polls
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  postgres_data:
